### ISSUE TITLE
since V10 import of non-English language export gives 'too many values to unpack'

### ISSUE THREAD

**Issue by clarkejj** [frappe/erpnext#12578]
V10 import export of English works but not for other languages:

in v9 import export of Thai language data worked but not now in v10
https://discuss.erpnext.com/t/unable-to-import-data-too-many-values-to-unpack/32355/7

v10 import export of Turkish language data error
https://discuss.erpnext.com/t/erpnext-10-data-import-error-from-template-excel-file/32808/7

**Comment by manassolanki** [comment]
hi @clarkejj 
Could you comment the version of frappe and full error log? We have already fixed language related issue.

**Comment by clarkejj** [comment]
Thanks Manas I have requested and will forward those when the users inform me

**Comment by clarkejj** [comment]
Neither user responded with a traceback so close this problem report for now...

**Comment by Salmon-Bard** [comment]
The problem still have not been fixed and this issue is annoying since you have to switch your language for import to work.

**Comment by clarkejj** [comment]
If you provide this info as requested that will help troubleshoot your case - also for what language too, that might help too?

"Could you comment the version of frappe and full error log? We have already fixed language related issue."

**Comment by Salmon-Bard** [comment]
Thanks for replying 

I'm importing from Urdu and I've tested other languages
The issue is in the importer processes where it assumes that columns headers are in English matching the values set in database for the labels

but the columns headers are actually in local language used in ERPNEXT UI. 

This is still present in latest version I've tested last week

**Comment by clarkejj** [comment]
Thanks very much for your reply with details, I will reopen this.  

For good measure perhaps Subscribe to receive Notices where you may want to respond.

**Comment by Wjp43045** [comment]
@clarkejj Hello, I am using frappe 10.1.70. I also got this error. How can I fix it?
Thanks

**Comment by clarkejj** [comment]
Best to post your issue **with error traceback** to https://discuss.erpnext.com/ with a link to this here.

This may be an environment problem for dialogue to vet and resolve. thanks

**Comment by Wjp43045** [comment]
@clarkejj I only used frappe and didn't use ERP. Can I post my question at https://discuss.erpnext.com/?

**Comment by clarkejj** [comment]
ok yes perhaps post on both, since https://discuss.frappe.io receives much less traffic visibility for response and contribution...

**Comment by mohamadosama** [comment]
I faced this problem and could solve it by trick:

**Solution:**
1. Copy all the data from the excel file
2. Paste it to a google spread sheet document (Or just upload the Excel file and convert it to Google Spread Sheet)
3. Sellect all, format>clear formatting
4. download the file as csv
5. never open it on excel on your desktop
6. then import it to the system, and Arabic letters will be fine.

**Comment by clarkejj** [comment]
Thanks for sharing!  To post your workaround to discuss.erpnext.com will inform lots more folks than are likely to happen on this learning here thanks!
