### ISSUE TITLE
Easy Install install.py issue

### ISSUE THREAD

**Issue by Goeppert** [frappe/erpnext#19486]
Many users are reporting the following problem with the easy install procedure:

https://discuss.erpnext.com/t/i-always-get-this-error-with-easy-install/54475/8
https://discuss.erpnext.com/t/easy-install-guide-not-working/54457/10
https://discuss.erpnext.com/t/error-while-installation-on-fresh-ubuntu-18-04-fresh-install/54334/10

I've also reproduced this error.

**Comment by joogletech** [comment]
Am also getting this error

**Comment by flexy2ky** [comment]
I got this error too. I've tried manual install too but installation fails on bench init

**Comment by Goeppert** [comment]
I fixed this by replacing the following line in install.py

    'pip': "sudo pip install --upgrade setuptools cryptography ansible pip"

with

    'pip': "sudo pip install --upgrade setuptools cryptography ansible==2.8.5.0 pip"

**Comment by bertbouwknegt** [comment]
I Also have this error

**Comment by gavindsouza** [comment]
hey @Goeppert 

> ```
> 'pip': "sudo pip install --upgrade setuptools cryptography ansible==2.8.5.0 pip"
> ```

if pinning down the ansible version helps, why don't you open a PR. Either that or get it working for the latest version of ansible. I can review it then and get it fixed for everyone.

**Comment by bertbouwknegt** [comment]
RUNNING HANDLER [mariadb : restart mysql] **************************************
task path: /tmp/.bench/playbooks/roles/mariadb/handlers/main.yml:2

PLAY RECAP *********************************************************************
localhost                  : ok=30   changed=20   unreachable=0    failed=1    skipped=21   rescued=0    ignored=0

Traceback (most recent call last):
  File "install.py", line 413, in <module>
    install_bench(args)
  File "install.py", line 135, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 327, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2
erp@erp:~$

Still fails...

**Comment by hpema** [comment]
Hi,

This is still failing.... Its failing on site creation on bench:

TASK [bench : Create a new site] *********************************************************************************************
task path: /tmp/.bench/playbooks/roles/bench/tasks/setup_erpnext.yml:17
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/tmp/ansible-tmp-1572877496.830638-160930212103229 `" && echo ansible-tmp-1572877496.830638-160930212103229="` echo /var/tmp/ansible-tmp-1572877496.830638-160930212103229 `" ) && sleep 0'
Using module file /usr/local/lib/python3.5/dist-packages/ansible/modules/commands/command.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-7840czg4i1dp/tmp6iifbitz TO /var/tmp/ansible-tmp-1572877496.830638-160930212103229/AnsiballZ_command.py
<127.0.0.1> EXEC /bin/sh -c 'setfacl -m u:frappe:r-x /var/tmp/ansible-tmp-1572877496.830638-160930212103229/ /var/tmp/ansible-tmp-1572877496.830638-160930212103229/AnsiballZ_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S -n  -u frappe /bin/sh -c '"'"'echo BECOME-SUCCESS-bdvqpwafafveurzmxhoaxsohpkxnooga ; /usr/bin/python3 /var/tmp/ansible-tmp-1572877496.830638-160930212103229/AnsiballZ_command.py'"'"' && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /var/tmp/ansible-tmp-1572877496.830638-160930212103229/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": [
        "bench",
        "new-site",
        "erp.local",
        "--admin-password",
        "gauranga",
        "--mariadb-root-password",
        "gauranga"
    ],
    "delta": "0:00:45.085460",
    "end": "2019-11-04 16:25:42.313776",
    "invocation": {
        "module_args": {
            "_raw_params": "bench new-site erp.local --admin-password 'gauranga' --mariadb-root-password 'gauranga'",
            "_uses_shell": false,
            "argv": null,
            "chdir": "/home/frappe/frappe-bench",
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2019-11-04 16:24:57.228316",
    "stderr": "Traceback (most recent call last):\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 484, in connect\n    sock = self._connect()\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 541, in _connect\n    raise err\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 529, in _connect\n    sock.connect(socket_address)\nConnectionRefusedError: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/client.py\", line 2879, in execute\n    return execute(conn, stack, raise_on_error)\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/client.py\", line 2749, in _execute_transaction\n    connection.send_packed_command(all_cmds)\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 585, in send_packed_command\n    self.connect()\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 489, in connect\n    raise ConnectionError(self._error_message(e))\nredis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 484, in connect\n    sock = self._connect()\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 541, in _connect\n    raise err\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 529, in _connect\n    sock.connect(socket_address)\nConnectionRefusedError: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.5/runpy.py\", line 184, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"/usr/lib/python3.5/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 97, in <module>\n    main()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 18, in main\n    click.Group(commands=commands)(prog_name='bench')\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 764, in __call__\n    return self.main(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 717, in main\n    rv = self.invoke(ctx)\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 1137, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 956, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 555, in invoke\n    return callback(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py\", line 32, in new_site\n    db_type=db_type)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py\", line 73, in _new_site\n    _install_app(app, verbose=verbose, set_as_patched=not source_sql)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/installer.py\", line 92, in install_app\n    frappe.get_attr(after_install)()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/install.py\", line 19, in after_install\n    install_basic_docs()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/install.py\", line 77, in install_basic_docs\n    frappe.get_doc(d).insert()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 259, in insert\n    self.run_post_save_methods()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 919, in run_post_save_methods\n    self.run_method(\"on_update\")\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 787, in run_method\n    out = Document.hook(fn)(self, *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 1058, in composer\n    return composed(self, method, *args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 1041, in runner\n    add_to_return_value(self, fn(self, *args, **kwargs))\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 781, in <lambda>\n    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py\", line 93, in on_update\n    self.share_with_self()\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py\", line 177, in share_with_self\n    flags={\"ignore_share_permission\": True})\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/share.py\", line 44, in add\n    notify_assignment(user, doctype, name, everyone)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/share.py\", line 171, in notify_assignment\n    enqueue_create_notification(shared_by, notification_doc)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/desk/doctype/notification_log/notification_log.py\", line 38, in enqueue_create_notification\n    now=frappe.flags.in_test\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 1475, in enqueue\n    return frappe.utils.background_jobs.enqueue(*args, **kwargs)\n  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py\", line 69, in enqueue\n    kwargs=queue_args)\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/rq/queue.py\", line 258, in enqueue_call\n    job = self.enqueue_job(job, at_front=at_front)\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/rq/queue.py\", line 331, in enqueue_job\n    pipe.execute()\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/client.py\", line 2894, in execute\n    return execute(conn, stack, raise_on_error)\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/client.py\", line 2749, in _execute_transaction\n    connection.send_packed_command(all_cmds)\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 585, in send_packed_command\n    self.connect()\n  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 489, in connect\n    raise ConnectionError(self._error_message(e))\nredis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.",
    "stderr_lines": [
        "Traceback (most recent call last):",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 484, in connect",
        "    sock = self._connect()",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 541, in _connect",
        "    raise err",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 529, in _connect",
        "    sock.connect(socket_address)",
        "ConnectionRefusedError: [Errno 111] Connection refused",
        "",
        "During handling of the above exception, another exception occurred:",
        "",
        "Traceback (most recent call last):",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/client.py\", line 2879, in execute",
        "    return execute(conn, stack, raise_on_error)",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/client.py\", line 2749, in _execute_transaction",
        "    connection.send_packed_command(all_cmds)",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 585, in send_packed_command",
        "    self.connect()",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 489, in connect",
        "    raise ConnectionError(self._error_message(e))",
        "redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused.",
        "",
        "During handling of the above exception, another exception occurred:",
        "",
        "Traceback (most recent call last):",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 484, in connect",
        "    sock = self._connect()",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 541, in _connect",
        "    raise err",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 529, in _connect",
        "    sock.connect(socket_address)",
        "ConnectionRefusedError: [Errno 111] Connection refused",
        "",
        "During handling of the above exception, another exception occurred:",
        "",
        "Traceback (most recent call last):",
        "  File \"/usr/lib/python3.5/runpy.py\", line 184, in _run_module_as_main",
        "    \"__main__\", mod_spec)",
        "  File \"/usr/lib/python3.5/runpy.py\", line 85, in _run_code",
        "    exec(code, run_globals)",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 97, in <module>",
        "    main()",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py\", line 18, in main",
        "    click.Group(commands=commands)(prog_name='bench')",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 764, in __call__",
        "    return self.main(*args, **kwargs)",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 717, in main",
        "    rv = self.invoke(ctx)",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 1137, in invoke",
        "    return _process_result(sub_ctx.command.invoke(sub_ctx))",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 1137, in invoke",
        "    return _process_result(sub_ctx.command.invoke(sub_ctx))",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 956, in invoke",
        "    return ctx.invoke(self.callback, **ctx.params)",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/click/core.py\", line 555, in invoke",
        "    return callback(*args, **kwargs)",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py\", line 32, in new_site",
        "    db_type=db_type)",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/commands/site.py\", line 73, in _new_site",
        "    _install_app(app, verbose=verbose, set_as_patched=not source_sql)",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/installer.py\", line 92, in install_app",
        "    frappe.get_attr(after_install)()",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/install.py\", line 19, in after_install",
        "    install_basic_docs()",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/install.py\", line 77, in install_basic_docs",
        "    frappe.get_doc(d).insert()",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 259, in insert",
        "    self.run_post_save_methods()",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 919, in run_post_save_methods",
        "    self.run_method(\"on_update\")",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 787, in run_method",
        "    out = Document.hook(fn)(self, *args, **kwargs)",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 1058, in composer",
        "    return composed(self, method, *args, **kwargs)",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 1041, in runner",
        "    add_to_return_value(self, fn(self, *args, **kwargs))",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py\", line 781, in <lambda>",
        "    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py\", line 93, in on_update",
        "    self.share_with_self()",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/user/user.py\", line 177, in share_with_self",
        "    flags={\"ignore_share_permission\": True})",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/share.py\", line 44, in add",
        "    notify_assignment(user, doctype, name, everyone)",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/share.py\", line 171, in notify_assignment",
        "    enqueue_create_notification(shared_by, notification_doc)",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/desk/doctype/notification_log/notification_log.py\", line 38, in enqueue_create_notification",
        "    now=frappe.flags.in_test",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py\", line 1475, in enqueue",
        "    return frappe.utils.background_jobs.enqueue(*args, **kwargs)",
        "  File \"/home/frappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py\", line 69, in enqueue",
        "    kwargs=queue_args)",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/rq/queue.py\", line 258, in enqueue_call",
        "    job = self.enqueue_job(job, at_front=at_front)",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/rq/queue.py\", line 331, in enqueue_job",
        "    pipe.execute()",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/client.py\", line 2894, in execute",
        "    return execute(conn, stack, raise_on_error)",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/client.py\", line 2749, in _execute_transaction",
        "    connection.send_packed_command(all_cmds)",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 585, in send_packed_command",
        "    self.connect()",
        "  File \"/home/frappe/frappe-bench/env/lib/python3.5/site-packages/redis/connection.py\", line 489, in connect",
        "    raise ConnectionError(self._error_message(e))",
        "redis.exceptions.ConnectionError: Error 111 connecting to localhost:11000. Connection refused."
    ],
    "stdout": "Creating Database...\n\nInstalling frappe...\n\rUpdating DocTypes for frappe        : [                                        ]\rUpdating DocTypes for frappe        : [                                        ]\rUpdating DocTypes for frappe        : [                                        ]\rUpdating DocTypes for frappe        : [========================================]",
    "stdout_lines": [
        "Creating Database...",
        "",
        "Installing frappe...",
        "",
        "Updating DocTypes for frappe        : [========================================]"
    ]
}

PLAY RECAP *******************************************************************************************************************
localhost                  : ok=79   changed=46   unreachable=0    failed=1    skipped=52   rescued=0    ignored=0

Traceback (most recent call last):
  File "install.py", line 413, in <module>
    install_bench(args)
  File "install.py", line 135, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 327, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2

**Comment by Goeppert** [comment]
Work for me now.  Thanks for updating so quickly.

**Comment by worldofsmarty** [comment]
@Goeppert What did you do to get the script to work.

**Comment by Goeppert** [comment]
Here is the installation procedure I used on a fresh install of Ubuntu 18.04:

sudo apt-get -y update 
sudo apt-get -y upgrade
sudo apt-get -y install python 
sudo apt install libssl1.0-dev
sudo apt-get -y dist-upgrade
sudo reboot

wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py

sudo adduser frap
sudo usermod -aG sudo frap
sudo python install.py --production --user frap --site xxx.com --version 11

**Comment by Thunderbottom** [comment]
https://github.com/frappe/frappe/commit/ebeee1232666dd1da5e8abac0421be0e7c39d492 should fix the issue.

**Comment by Thunderbottom** [comment]
https://github.com/frappe/frappe/commit/ebeee1232666dd1da5e8abac0421be0e7c39d492 should fix the issue caused during new-site

**Comment by worldofsmarty** [comment]
But how to install Erpnext v12

**Comment by Thunderbottom** [comment]
you can try using the [easy_install script](https://github.com/frappe/bench#easy-install), which should setup version 12 by default.

**Comment by bertbouwknegt** [comment]
Still failes...


RUNNING HANDLER [mariadb : restart mysql] **************************************
task path: /tmp/.bench/playbooks/roles/mariadb/handlers/main.yml:2

PLAY RECAP *********************************************************************
localhost                  : ok=30   changed=19   unreachable=0    failed=1    skipped=21   rescued=0    ignored=0

Traceback (most recent call last):
  File "install.py", line 413, in <module>
    install_bench(args)
  File "install.py", line 135, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 327, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2
erp@erp:~$
