### ISSUE TITLE
Not Able to Open the doctype Batch. After navigating to batch list, not able to open individual batch IDs.

### ISSUE THREAD

**Issue by knaveenhyperbaric** [frappe/erpnext#32889]
### Information about bug

Not Able to Open the doctype Batch. After navigating to batch list, not able to open individual batch IDs.

### Module

stock

### Version

ERPNext: v14.4.0 (HEAD)

ERPNext Support: v0.2.1 (HEAD)

Frappe Framework: v14.13.0 (HEAD)

Frappe HR: v1.0.0 (HEAD)

Journeys: v0.0.1 (HEAD)

Payments: v0.0.1 (HEAD)

![image](https://user-images.githubusercontent.com/117721538/200521808-a330be6f-86a7-4443-bda7-e02324cd8600.png)

**Comment by muchai** [comment]
It's because of the forward slashes.

It's fixed here though: https://github.com/frappe/frappe/issues/18659

I see a release of the same today, hopefully.

**Comment by knaveenhyperbaric** [comment]
Thanks for your help. 

 

Thank You.

Best Regards,


Naveenkumar M

Purchase Team
Ph: 044-42116555/ 22501157

 


 <https://hyperbaric-chamber.com/> 

INDIA
Tekna Manufacturing Pvt. Ltd.,
C19, Industrial Estate,
Guindy, Chennai, India - 600032
Ph No. +91-44-42116555

**Comment by knaveenhyperbaric** [comment]
Thanks for your help

 

Thank You.

Best Regards,


Naveenkumar M

Purchase Team
Ph: 044-42116555/ 22501157

 


 <https://hyperbaric-chamber.com/> 

INDIA
Tekna Manufacturing Pvt. Ltd.,
C19, Industrial Estate,
Guindy, Chennai, India - 600032
Ph No. +91-44-42116555

**Comment by knaveenhyperbaric** [comment]
Still the problem remains the same. 

 

Thank You.

Best Regards,


Naveenkumar M

Purchase Team
Ph: 044-42116555/ 22501157

 


 <https://hyperbaric-chamber.com/> 

INDIA
Tekna Manufacturing Pvt. Ltd.,
C19, Industrial Estate,
Guindy, Chennai, India - 600032
Ph No. +91-44-42116555

	

 

 

From: Naveenkumar Muthusamy ***@***.*** 
Sent: 09 November 2022 09:32
To: 'frappe/erpnext' ***@***.***>; 'frappe/erpnext' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [frappe/erpnext] Not Able to Open the doctype Batch. After navigating to batch list, not able to open individual batch IDs. (Issue #32889)

 

Thanks for your help

 

Thank You.

Best Regards,


Naveenkumar M

Purchase Team
Ph: 044-42116555/ 22501157

 


 <https://hyperbaric-chamber.com/> 

INDIA
Tekna Manufacturing Pvt. Ltd.,
C19, Industrial Estate,
Guindy, Chennai, India - 600032
Ph No. +91-44-42116555

**Comment by knaveenhyperbaric** [comment]
https://user-images.githubusercontent.com/117721538/200829284-bf84a0f4-5f54-402c-a635-9792f351ee51.mp4

the issue still remains same
