### ISSUE TITLE
Establish a connection between sales orders, sales invoices, delivery notes, and shipments

### ISSUE THREAD

**Issue by DIMPSINGH** [frappe/erpnext#36955]
Hi Team,

We are aiming to establish a connection between sales orders, sales invoices, delivery notes, and shipments. Our objective is to enable the ability to easily navigate between these related documents. Whether it's a sales order, sales invoice, or delivery note, we envision the capacity to access links to other pertinent documents. This interconnectedness would provide accessibility to all linked documents from any individual document.

we have noticed instances where delivery notes are correctly linked to sales orders, and sales orders are linked to sales invoices. However, the connection between the delivery note and the sales invoice is not visible.

We kindly request your assistance in implementing this functionality.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anandbaburajan** [comment]
> the connection between the delivery note and the sales invoice is not visible

@DIMPSINGH this was fixed in https://github.com/frappe/erpnext/pull/36183 and was released in v14.34.0. Which version are you on?

**Comment by DIMPSINGH** [comment]
Hi Anand,

We are using v14.37.0  as of now.

Thanks,
Dimple
________________________________

**Comment by anandbaburajan** [comment]
@DIMPSINGH can you share your site's current version of the framework? This issue is fixed in v14.44.0 and above of the framework. If the framework's version is not the problem either, please check the connections between the delivery note and sales invoice one more time and if the issue persists, please share some screenshots since I'm not able to reproduce the issue on the latest v14 version of erpnext and the framework.

**Comment by DIMPSINGH** [comment]
Hi Anand,
We are using ERPNext with link https://rareworks.frappe.cloud/

Along with that, attached is the screenshot for version of our system.

We still facing this issue in this version.

[cid:80818092-c88d-4c8e-8205-c922dc53dc54]

If you have added this feature to your new version,
Please update our site to latest one.

Thanks,
Dimple
________________________________

**Comment by anandbaburajan** [comment]
@DIMPSINGH I can see connections between DN and SI on your site. Please check these two connected documents: https://rareworks.frappe.cloud/app/sales-invoice/SI-23-05-66-1 and https://rareworks.frappe.cloud/app/delivery-note/DN-23-00337.
