### ISSUE TITLE
Bank reconciliation tools error

### ISSUE THREAD

**Issue by eebene** [frappe/erpnext#40493]
### Information about bug

When trying to do a bank reconciliation using the reconciliation tool the following error is generated when I click on actions for any transaction:

"exception": "TypeError: get_matching_queries() takes from 5 to 11 positional arguments but 12 were given",
	"exc_type": "TypeError",
	"_exc_source": "erpnext (app)""

### Module

accounts

### Version

"erpnext": "15.17.0",
	"frappe": "15.17.3",
	"hrms": "15.13.0",
	"print_designer": "1.0.0"

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.17.0",
	"frappe": "15.17.3",
	"hrms": "15.13.0",
	"print_designer": "1.0.0"
}
```
### Route
```
Form/Bank Reconciliation Tool/Bank Reconciliation Tool
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1716, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/doctype/bank_reconciliation_tool/bank_reconciliation_tool.py", line 471, in get_linked_payments
    matching = check_matching(
               ^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/doctype/bank_reconciliation_tool/bank_reconciliation_tool.py", line 523, in check_matching
    queries = get_queries(
              ^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/doctype/bank_reconciliation_tool/bank_reconciliation_tool.py", line 566, in get_queries
    frappe.get_attr(method_name)(
TypeError: get_matching_queries() takes from 5 to 11 positional arguments but 12 were given

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"bank_transaction_name": "ACC-BTN-2024-00983",
		"document_types": "[\"payment_entry\",\"journal_entry\"]",
		"from_date": "2024-02-01",
		"to_date": "2024-03-16",
		"filter_by_reference_date": 0
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/erpnext.accounts.doctype.bank_reconciliation_tool.bank_reconciliation_tool.get_linked_payments",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "TypeError: get_matching_queries() takes from 5 to 11 positional arguments but 12 were given",
	"exc_type": "TypeError",
	"_exc_source": "erpnext (app)"
}
```
```

**Comment by this-gavagai** [comment]
The issue seems to be this pull request, which added a 12th parameter:
https://github.com/frappe/erpnext/commit/711b72b26c57f654601243066e1e8ad08b246a42

@ruthra-kumar any suggestions?

**Comment by ruthra-kumar** [comment]
@this-gavagai 
Upgrading HRMS to v15.13.1 should fix it.
https://github.com/frappe/hrms/pull/1518#issuecomment-1994092290

**Comment by this-gavagai** [comment]
Should, perhaps, but doesn't seem to. @ruthra-kumar 

<img width="1154" alt="Screenshot 2024-03-19 at 11 46 49 AM" src="https://github.com/frappe/erpnext/assets/9303694/98bf3f01-67ad-4c9b-b89e-221adb8205f1">
<img width="1246" alt="Screenshot 2024-03-19 at 11 46 34 AM" src="https://github.com/frappe/erpnext/assets/9303694/6df9c86d-5d02-47db-aa71-795e36734ae7">

**Comment by ruthra-kumar** [comment]
traceback?

**Comment by this-gavagai** [comment]
I do have hrms installed, but the error stack has no mention of it.
Edited to add: for what it's worth, I haven't been able to pinpoint the issue. The call at line 566 does seem to have 12 arguments, but I struggle to read code that has a lot of `frappe.get_attrs` calls. I've cleared cache, restarted redis, etc., but I'm still seeing this error.

```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1716, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/bank_reconciliation_tool/bank_reconciliation_tool.py", line 471, in get_linked_payments
    matching = check_matching(
  File "apps/erpnext/erpnext/accounts/doctype/bank_reconciliation_tool/bank_reconciliation_tool.py", line 523, in check_matching
    queries = get_queries(
  File "apps/erpnext/erpnext/accounts/doctype/bank_reconciliation_tool/bank_reconciliation_tool.py", line 566, in get_queries
    frappe.get_attr(method_name)(
TypeError: get_matching_queries() takes 11 positional arguments but 12 were given
```

**Comment by ruthra-kumar** [comment]
If you have access to code, add `print(method_name)` on line 566 and replicate. It should print the exact method that is being called.

**Comment by this-gavagai** [comment]
I have access to the code but not stdout (it's a production site using supervisor, etc.)  Is there an easy way to access debugging messages like this?

**Comment by this-gavagai** [comment]
Okay, digging around, it seems to be the Lending app that's causing problems.

https://github.com/frappe/lending/blob/655a83d3302fa2c96c528e310f996ab0744d5e7f/lending/loan_management/utils.py#L80

I feel the need to say, it's pretty wild to be issuing API changes in a x.x.1 patch release. I have to think there's a better way...
