### ISSUE TITLE
Unable to Post Exchange Rate Revaluation Entry for Zero Balance in Account Currency

### ISSUE THREAD

**Issue by parasonit** [frappe/erpnext#42052]
### Issue Description
When the Balance in Account Currency is zero but there is an amount in base currency, ERPNext does not handle the exchange rate revaluation entry correctly. This prevents posting the revaluation entry for the difference amount.

### Steps to Reproduce
1. Create a foreign currency transaction.
2. Ensure that the Balance in Account Currency is zero.
3. Verify that there is an amount in the base currency.
4. Attempt to post an Exchange Rate Revaluation Entry for the difference amount.

### Expected Result
The system should allow posting the revaluation entry and correctly handle the difference amount between the account currency and the base currency.

### Actual Result
We have posted one transaction with a balance in the Account and Base currency. system posted the revaluation for this correctly but when there is zero balance in account currency the system throws an error or does not handle the revaluation entry properly. Please refer below screenshot

### Screenshots
![Exchange Gain loss Error](https://github.com/frappe/erpnext/assets/118710551/8a2e5559-a53c-42f9-bf37-6d326e81d0ff)

### Suggested Fix
Review the handling of exchange rate revaluation entries when the balance in the account currency is zero but there is a balance in the base currency. Ensure the system can post the revaluation entry correctly.

### Module

accounts

### Version

Frappe Framework: v15.29.0 (version-15)
ERPNext: v15.27.2 (version-15)

### Installation method

manual install

**Comment by dpw1460e** [comment]
Same on my end.

I have a USD account with balance 0, but the base currency EUR holds a balance of €36.21 to be posted as exchange rate losses.

Whatever I try, ERPNext tells me “Row 1: Both Debit and Credit values cannot be zero”, which is because of the USD balances being 0.

 Even trying to create a journal entry myself did not work.

According to [https://github.com/frappe/erpnext/issues/32353](https://github.com/frappe/erpnext/issues/32353) this issue should have been resolved.

**Version**
ERPNext: v15.59.0 (version-15)
Frappe Framework: v15.66.1 (version-15)

Hopefully, this could be solved quick as of the old bug report already closed.

Thanks for your help.

**Comment by JeansReal** [comment]
+1 this problem still exists, also affecting multi currency payment entries

**Comment by dpw1460e** [comment]
I still didn't find a solution about how to get rid off the outstanding EUR balance for a zero balanced USD vendor account.

**Comment by frederictobien** [comment]
We face the same issue


Version
Frappe Framework: v15.112.1 (version-15)

ERPNext: v15.112.0 (version-15)
