### ISSUE TITLE
Unable to transition to Closed status in Purchase Order Workflow

### ISSUE THREAD

**Issue by Guru107** [frappe/erpnext#50563]
### Information about bug

There is a Close action in Purchase Order, how do I get to implement that in a workflow. Currently it won’t allow to transition from Receive and Bill status to closed.

<img width="881" height="376" alt="Image" src="https://github.com/user-attachments/assets/b0f62cc9-faf9-4712-b1a7-303d9c7ef3af" />

<img width="883" height="386" alt="Image" src="https://github.com/user-attachments/assets/53e2bf02-bdef-4b36-9106-6d23bf32a3df" />

On clicking the Close workflow action, we get the below error

<img width="910" height="139" alt="Image" src="https://github.com/user-attachments/assets/f1d20a5e-32c7-4f0f-bbd9-3799f21fb65b" />

<img width="564" height="137" alt="Image" src="https://github.com/user-attachments/assets/f6f657b7-a27e-4744-a855-24fd52b5d517" />

How can we **Close** the Purchase Order using the workflow action?

<img width="881" height="111" alt="Image" src="https://github.com/user-attachments/assets/d9fa2d3d-1096-417b-923d-9b608ff45d4f" />

### Module

buying

### Version

ERPNext: v15.79.2 (version-15)

Frappe Framework: v15.82.1 (version-15)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

```shell

```

**Comment by TalhaButt2508** [comment]
Hi,
Use the following:
Compare and see where you're missing it becuase i can close it **from system's default close.**
**No need to manually add the close transition or state**
_(Dont get confused with once approve by user and then by manager , i have implemented condition based approval)_

<img width="1224" height="875" alt="Image" src="https://github.com/user-attachments/assets/aef8ce75-7f3d-4d1d-9af9-5814c4c1b1cb" />

**Comment by Guru107** [comment]
> Hi, Use the following: Compare and see where you're missing it becuase i can close it **from system's default close.** **No need to manually add the close transition or state** _(Dont get confused with once approve by user and then by manager , i have implemented condition based approval)_
> 
> <img alt="Image" width="1224" height="875" src="https://private-user-images.githubusercontent.com/222021902/515085049-aef8ce75-7f3d-4d1d-9af9-5814c4c1b1cb.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMzNzU4MjgsIm5iZiI6MTc2MzM3NTUyOCwicGF0aCI6Ii8yMjIwMjE5MDIvNTE1MDg1MDQ5LWFlZjhjZTc1LTdmM2QtNGQxZC05YWY5LTU4MTRjNGMxYjFjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTExN1QxMDMyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODhmZmI3ZmY5YjM4OWUxYjViNjg0ODMwNjFjNWFkNzgzZDIyZjI4NjcwZjE0MjY3ZjQ4ZjA3NmZkYjY1ZGQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SWfZiit4BEzZ8fyCYMhW4J-u581IJjRhxpFupHrkF3s">

When you use **system's default close button** to close the PO, it won't update the Workflow State, so for example if a PO is closed using system default close button, we will still see the "Approved" state in the PO list view as workflow_state will still be Approved, it confuses the users, when they will look at the list view and see Approved for a Closed PO.

**Comment by TalhaButt2508** [comment]
If you are only concerned about viewing the list of approved Purchase Orders,
Filter the list/report in following way:

<img width="600" height="266" alt="Image" src="https://github.com/user-attachments/assets/28dc611c-ecf7-449c-b225-c11bfcbb26c7" />

or else just add a transition from Approved , action : close , Closed
vice versa for open

<img width="1401" height="818" alt="Image" src="https://github.com/user-attachments/assets/69936eab-d63e-4f41-ab74-f1bc99bc6418" />

**Comment by DipenFrappe** [comment]
I think you need to customise it as a status is a button and not a field, which you can update via workflow.

We are planning to add status as a button. Once that is done, you will be able to do it through workflow, but for now needs customisation
