### ISSUE TITLE
Cannot refer journal entries while making Payment Entry

### ISSUE THREAD

**Issue by mfazilp** [frappe/erpnext#5949]
Hello,

Cannot refer journal entries while making payment entry. I got the following error,

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 876, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 586, in get_reference_details
    exchange_rate = get_exchange_rate(party_account_currency, ref_doc.company_currency)
UnboundLocalError: local variable 'ref_doc' referenced before assignment

**Comment by nabinhait** [comment]
Checked the code, did not found any issue. Are you on the latest version?

**Comment by mfazilp** [comment]
Yes on latest version. If i making payment entry for a customer having account receivable i got the following error while saving it,

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 242, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 269, in _save
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 687, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 638, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 816, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 632, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 38, in validate
    self.set_missing_values()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 100, in set_missing_values
    self.set_missing_ref_details()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 107, in set_missing_ref_details
    d.reference_name, self.party_account_currency)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 586, in get_reference_details
    exchange_rate = get_exchange_rate(party_account_currency, ref_doc.company_currency)
UnboundLocalError: local variable 'ref_doc' referenced before assignment

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 876, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
    doc.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 242, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 269, in _save
    self.run_before_save_methods()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 687, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 638, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 816, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 799, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 632, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 38, in validate
    self.set_missing_values()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 100, in set_missing_values
    self.set_missing_ref_details()
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 107, in set_missing_ref_details
    d.reference_name, self.party_account_currency)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_entry/payment_entry.py", line 586, in get_reference_details
    exchange_rate = get_exchange_rate(party_account_currency, ref_doc.company_currency)
UnboundLocalError: local variable 'ref_doc' referenced before assignment

**Comment by nabinhait** [comment]
fixed via #5967

**Comment by mfazilp** [comment]
Dear Nabin, 

Its get fixed. Thank you. Now when we receive an half amount of amount receivable. For eg: We got payment 2000 from a customer having 4900 in account receivable.

We made the payment entry with 2000 amount received. When we submit, it shows Differnce amount should be zero. That means payment should be received fully or we cannot make half of the payment.

**Comment by nabinhait** [comment]
Please provide a screenshot

**Comment by mfazilp** [comment]
Attached pictures. Referred amount from journal entry is about 4298. But customer paid only 2000. Its saved and submit give this message. 

![screenshot from 2016-08-02 16-32-18](https://cloud.githubusercontent.com/assets/8024554/17330289/f99f142a-58ce-11e6-9e92-7e44a290907d.png)
![screenshot from 2016-08-02 16-32-35](https://cloud.githubusercontent.com/assets/8024554/17330290/f9a5c9e6-58ce-11e6-93e9-064ce95ff973.png)

**Comment by mfazilp** [comment]
Nabin,

I made changes for those two files mentioned above. But still the same message pop up if paid amount is different than Party balance for a particular journal entry

**Comment by mfazilp** [comment]
Dear nabin,

any update on this?

**Comment by nabinhait** [comment]
Can't replicate the issue. Are you getting the same issue in new Payment Entry as well? Or is it only in this existing Payment Entry?

**Comment by mfazilp** [comment]
I check with old entry. let me try to make a new entry and check.

**Comment by mfazilp** [comment]
Thanks man. for new entry it was okay.
