### ISSUE TITLE
Reconcile negative invoices via Payment Reconciliation tool.

### ISSUE THREAD

**Issue by ai-erp** [frappe/erpnext#6091]
I would like to suggest that upon making credit/debit notes for certain sales invoice and purchase invoices which was previously paid or receipted, the link on payment/receipt should be removed since the credit note has been linked to that Sales Invoice or Purchase Invoices. It is because I have noticed some bug relating to making payment reconciliation.
The receipt/payment previously linked to a Sales Invoice/Purchase Invoice was already allocated to it. And when Credit Note/Debit note has been issued, the same is applied to the same document leaving a negative balance on that Invoice.
By that we can reconcile again the receipt and payment vouchers related that invoice on the remaining amount it should be allocated for that invoice.

Correct me if I'm wrong... 
Thank you...

**Comment by ai-erp** [comment]
For Addtional info, please refer to https://discuss.erpnext.com/t/suggestion-for-making-credit-debit-notes-applied-to-invoices-affecting-invoices-previously-paid-collected/10321

**Comment by SonaliBudhrani** [comment]
+1

**Comment by SonaliBudhrani** [comment]
We too were facing this same issue and had to pass a Journal entry to transfer the negative balance from Invoice to some other Invoice that was due -
In the first row, select Debtor account, Customer and Sales Invoice with positive outstanding (SINV-00100). Enter Credit value.
In the second row, select Debtor account, Customer and Sales Invoice against which Credit Note was created (SINV-00099). Enter same Debit value.
Save and Submit.
With this Journal Entry, your Sales Invoice SINV-00100 will be updated as paid. Also, the negative balance for SINV-00099 will be reduced or become zero (if it is completely adjusted against new invoice).

**Comment by SonaliBudhrani** [comment]
I would suggest that if we could get this sales invoice with negative balance in **payment reconciliation**, It would make things very easy. Then we would be able to adjust that negative balance to some other overdue Invoice directly.

**Comment by anasanzari** [comment]
+1

**Comment by dj12djdjs** [comment]
+1

**Comment by dj12djdjs** [comment]
@Anuja-pawar Is there a link where this has been resolved? I know in V12 this problem still exists. Not sure about V13 yet.

**Comment by Anuja-pawar** [comment]
@dj12djdjs Sorry, couldn't find a link as it has been resolved a while ago, we can reconcile negative invoices (credit/debit note) through payment reconciliation tool in both v12 & v13, hence closed it.
May I know what issue you're talking about here?

**Comment by dj12djdjs** [comment]
@Anuja-pawar I just tested again on V13.9.2 and we cannot reconcile negative invoices. Please see the example below.

In May we invoice customer $175.14  Invoice #: AC7192
In April the customer pays the amount on the statement.
Then in August customer returns these items. We issue credit note against AC7192 making the outstanding amount from $0.00 to $-175.14

In payment entry you can see AC7192 as a payment towards the account.
![image](https://user-images.githubusercontent.com/29856401/131686967-7c74313d-4a8e-4656-bef4-c96882633697.png)

Now if we check payment reconciliation tool. AC7192 is not available to reconcile.
![image](https://user-images.githubusercontent.com/29856401/131687152-084d71cc-8378-4acb-8e50-d106824f6b82.png)

This is a problem because the only way to clear this is by Payment Entry. The only way we can do this is to collect payment from the customer. We are sending the customer there balance for August the statement will now show AC7192 from May. This is very confusing to the customer. We should be able to reconcile this against existing invoices in August before sending the customer their statement.

**Comment by Anuja-pawar** [comment]
@dj12djdjs Yep, I could replicate the issue on version 12, so we have refactored the entire tool for version 13 - https://github.com/frappe/erpnext/pull/27284, you would be able to reconcile credit/debit notes too. It will be deployed in the upcoming release. 
Also, I'll try to get this fixed for version 12 as soon as I can

**Comment by Ponyooooo** [comment]
@dj12djdjs have you solved this issue for the V12? the credit note and debit notes with the negative outstanding amount still does not appear as a floating payment on the payment reconciliation.

However, the stand-alone credit and debit notes appear on the payment reconciliation tool. Do you have any idea on what v12 it is solved?
