### ISSUE TITLE
AttributeError thrown on Production Planning Tool

### ISSUE THREAD

**Issue by NlightNFotis** [frappe/erpnext#6921]
Hello,

Using the Production Planning Tool to create a new materials request, we get thrown this exception:

```
Traceback (most recent call last):   
File "/home/www/frappe-bench/apps/frappe/frappe/app.py", line 55, in application    
 response = frappe.handler.handle()   
File "/home/www/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle     
 execute_cmd(cmd)   
File "/home/www/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd     
 ret = frappe.call(method, **frappe.form_dict)   
File "/home/www/frappe-bench/apps/frappe/frappe/__init__.py", line 890, in call     
 return fn(*args, **newargs)   
File "/home/www/frappe-bench/apps/frappe/frappe/handler.py", line 67, in runserverobj      
 frappe.desk.form.run_method.runserverobj(method, docs=docs, dt=dt, dn=dn, arg=arg, args=args) 
File "/home/www/frappe-bench/apps/frappe/frappe/desk/form/run_method.py", line 35, in runserverobj 
 r = doc.run_method(method)   
File "/home/www/frappe-bench/apps/frappe/frappe/model/document.py", line 654, in run_method       
 out = Document.hook(fn)(self, *args, **kwargs)   
File "/home/www/frappe-bench/apps/frappe/frappe/model/document.py", line 882, in composer      
 return composed(self, method, *args, **kwargs)   
File "/home/www/frappe-bench/apps/frappe/frappe/model/document.py", line 865, in runner     
 add_to_return_value(self, fn(self, *args, **kwargs))   
File "/home/www/frappe-bench/apps/frappe/frappe/model/document.py", line 648, in
 fn = lambda self, args, **kwargs: getattr(self, method)(args, **kwargs) 
File "/home/www/frappe-bench/apps/erpnext/erpnext/manufacturing/doctype/production_planning_tool/production_planning_tool.py", line 403, in raise_material_requests
 self.get_raw_materials(bom_dict,self.create_material_requests_non_stock_request) 
AttributeError: 'ProductionPlanningTool' object has no attribute 'create_material_requests_non_stock_request'
```

It seems that there is a reference to `self.create_material_requests_no_stock_request` but there is no such symbol in scope.

**Comment by dottenbr** [comment]
This important and essential tool is broken and doesn't work so we have to manually create material requests. This is a roadblock for us so we would much appreciate if this was hotfixed to the Master branch which is what we are using here.

**Comment by bcornwellmott** [comment]
create_material_requests_non_stock_request exists as one of the fields in the JSON file for the production planning tool, under the label **Include non-stock items**. Can you see that checkbox in the Production Planning Tool?

**Comment by NlightNFotis** [comment]
While I can see that field in the `production_planning_tool.json`, I can't see the checkbox appearing in the `Production Planning Tool` interface. Mind you, we haven't changed anything in the `Production Planning Tool` doctype.

**Comment by nabinhait** [comment]
Somehow Production Planning Tool has not reloaded, may be because modified timestamp is same in json and database. Changed modified timestamp in hotfix branch, it should fix the issue.

**Comment by NlightNFotis** [comment]
Preliminary testing shows that the fix applied **didn't** fix the issue. 

Does the whole process of the fix involve more things than just changing the timestamp? Because changing the timestamp alone doesn't fix it, and in case that the process is more elaborate, I couldn't find documentation on the whole process.

**Comment by dottenbr** [comment]
The issue is not resolved

**Comment by dottenbr** [comment]
I would like to push this again as very important. We are running Master branch and the production planning tool is broken which is a very essential thing to us moving forward. We are also getting nervous because we are blocking progress of 3 developers here right now. Please help us fix this in the master branch asap.

**Comment by nabinhait** [comment]
Please ping me on skype / screenhero, we can check via screen sharing.
